name: Rust

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build
      run: cargo build --verbose
#    - name: Run tests
#      run: for x in $(find vendor -type d -maxdepth 1); do cd "$x"; cargo test --verbose; cd ..; done ; cargo test
    - name: Run tests
      run: cargo test --verbose
